# Generated by Django 2.2 on 2020-10-02 23:55

import Course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('start_time', models.DateTimeField(verbose_name='上课时间')),
                ('end_time', models.DateTimeField(verbose_name='下课时间')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表管理',
                'db_table': 'LessonSchedule',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师管理',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='TermInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=50, verbose_name='学期名称')),
                ('start_date', models.DateField(verbose_name='学期开始日期')),
                ('end_date', models.DateField(verbose_name='学期结束日期')),
                ('week_counts', models.IntegerField(default=20, verbose_name='学期总周数')),
                ('current_week', models.IntegerField(default=1, verbose_name='当前周数')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期管理',
                'db_table': 'TermInfo',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Course.Teacher', verbose_name='教师姓名')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程名称管理',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (0, '星期日')], verbose_name='星期几')),
                ('weeks', Course.models.ListField(max_length=256, verbose_name='周次')),
                ('classroom', models.CharField(max_length=50, verbose_name='教室')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.LessonSchedule', verbose_name='节次')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期管理',
                'db_table': 'ClassSchedule',
            },
        ),
    ]
