# Generated by Django 2.2 on 2020-10-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_teacher_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表管理'},
        ),
        migrations.AlterModelOptions(
            name='lessonschedule',
            options={'verbose_name': '作息时间表', 'verbose_name_plural': '作息时间表管理'},
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_suspend',
            field=models.BooleanField(default=False, verbose_name='是否停课'),
        ),
    ]
