# Generated by Django 2.2 on 2020-10-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_remove_terminfo_current_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='end_time',
            field=models.TimeField(verbose_name='下课时间'),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='start_time',
            field=models.TimeField(verbose_name='上课时间'),
        ),
    ]
