# Generated by Django 2.2 on 2020-10-03 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20201003_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='assessment_method',
            field=models.CharField(choices=[('考试', '考试'), ('考查', '考查')], default='考查', max_length=10, verbose_name='考核方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course', verbose_name='课程名称'),
        ),
    ]
