# Generated by Django 2.2 on 2020-10-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20201003_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='assessment_method',
        ),
        migrations.AddField(
            model_name='course',
            name='assessment_method',
            field=models.CharField(choices=[('考试', '考试'), ('考查', '考查')], default='考查', max_length=10, verbose_name='考核方式'),
            preserve_default=False,
        ),
    ]
